In [16]:
import numpy as np

We talked about how numpy arrays, lists, and dictionaries are sent to functions as references and the values can be changed within the function.  I need to point out one danger, which is while values within these data types can be changed, if the variable name that is passed to a function is redefined within a function it can be overwritten.

In this first, example, as in class, values in a numpy array are changed within a function without using a return statement.

In [17]:
def change_me(x):
    x[0,0] = 99

In [18]:
y = np.arange(4).reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [19]:
change_me(y)
y

array([[99,  1],
       [ 2,  3]])

However, if a variable is defined within the function, here <code>x</code>, rather than referring to indivdual value within <code>x</code>, then <code>x</code> will refer to a new variable with scope only within the function.  That is, it will not change the variable <code>z</code> in the code below.

In [20]:
def change_me1(x):
    x = np.zeros((2,2))
    print(f'x within the function change_me1 is \n{x}')

In [21]:
z = np.arange(4).reshape(2,2)
change_me1(z)
print(f'z = \n{z}')

x within the function change_me1 is 
[[0. 0.]
 [0. 0.]]
z = 
[[0 1]
 [2 3]]
