# Import Packages and Load Data

In [3]:
import numpy as np
import mysql.connector as mysql
import time
import math

In [4]:
size=100

In [5]:
p = np.load(f'data/mnist1_{size}.npy').astype(np.float32)
q = np.load(f'data/mnist2_{size}.npy').astype(np.float32)
assert p.shape[0] == q.shape[0]
assert p.shape[1] ==784
assert q.shape[1] == 784

n = p.shape[0]
pixels = p.shape[1]

# Methods for Computing Distances

The methods shown below demonstrate a range of approaches for computing the pairwise distances between MNIST images in two data sets.  The available data sets contain either 10, 100, 1000, 10000, or 60000 images, each of which is constituted by 784 pixels encoded as floating-point values.  A data set with <code>n</code> images constitutes a <code>numpy</code> that is $n \times 784$.

## Base Python: Nested <code>for</code> Loops

In [20]:
start = time.time()
result = np.zeros((n,n)).astype(np.float32)
for i in range(n):
    for j in range(n):
        sum_sq = 0.0
        for k in range(pixels):
            sum_sq += (q[i][k] - p[j][k])**2
        result[i][j] = math.sqrt(sum_sq)

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 27.43082594871521 for 100x100
[10.553867 10.057241  8.833829  9.928223  8.737533]


## Linear Algebra Approach Using Matrix-Vector Math

In [6]:
start = time.time()
result = np.zeros((n,n)).astype(np.float32)
for i in range(n):
    for j in range(n):
        result[i][j] = np.sqrt(q[i]@q[i]-2*p[j]@q[i]+p[j]@p[j])

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 0.08700108528137207 for 100x100
[10.553867 10.057241  8.833829  9.928222  8.737532]


## Element-wise (Vectorized) Math with <code>numpy</code> and Nested <code>for</code> Loops

In [22]:
start = time.time()
result = np.zeros((n,n)).astype(np.float32)
for i in range(n):
    for j in range(n):
        result[i][j] = np.sqrt(((q[i]-p[j])**2).sum())

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 0.06618976593017578 for 100x100
[10.553867 10.057242  8.83383   9.928222  8.737532]


## <code>numpy np.newaxis()</code> to Avoid Loops via Broadcasting

In [23]:
start = time.time()
#result = np.sqrt((q-p)@(q-p).T)
result = np.sqrt(((q[:, np.newaxis, :] - p)*(q[:, np.newaxis, :] - p)).sum(axis=2))

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 0.02643442153930664 for 100x100
[10.553867 10.057242  8.83383   9.928222  8.737532]


## Using the <code>numpy</code> Method <code> np.linalg.norm()</code>

In [28]:
start = time.time()
#result = np.sqrt((q-p)@(q-p).T)
result = np.linalg.norm(q[:, np.newaxis, :] - p, axis=2)

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 2.137239694595337 for 1000x1000
[10.553867 10.057242  8.83383   9.928222  8.737532]


# Using the <code>scipy</code> Method <code> scipy.spatial.distance.cdist()</code>

In [29]:
from scipy.spatial.distance import cdist
start = time.time()
result = cdist(q,p)
print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result[0,:5])

Exec. time: 0.5108568668365479 for 1000x1000
[10.5538673  10.05724184  8.83382935  9.92822226  8.73753215]


# Introduction to <code>np.einsum()</code>

This <code>numpy</code> quickly multiplies arrays while summing across specified axis.  It requires as input a string in "Einstein Notation" that determines how the arrays will be multipled (e.g., vector-matrix multiplcation versus elementwise (vectorized) multiplication).

## Einstein Notation

Einstein notation give a roadmap for how <code>numpy</code> arrays and vectors are to be multiplied using single-characters each of which corresponds to a dimension (think rows and columns) of a <code>numpy</code> that is to be multiplied.  Further, when <code>np.einsum()</code> is used sums are often computed on the array that results from the specified multiplication operation.  

A typical example of Einstein notation is this:

``` python
'ij,jk->ik'
```

where

 - <code>i</code> represents the rows of the first input and <code>j</code> its column indices
 - <code>j</code> represents the rows of the second input and <code>k</code> its column indices
 - The symbol <code>-></code> separates inputs (on the left) from the output (on the right)
 - <code>ik</code> indicates that the output array has rows corresponding with the first input and columns corresponding with the second input.

As is demonstrated below, these two characteristics of the letters/indices used are important:

- The order of the indices in the Einstein notation
- Which indices used to represent the original inputs are either included in the specification fo the output, or not

The following page documents Einstien notation and gives examples: [link_fort_Einstein_Notation](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html)

first, we create two small arrays for demonstration.

In [14]:
mat1 = np.random.randint(0,10,(3,3))
mat2 = np.random.randint(0,10,(3,3))
print(mat1,'\n\n',mat2)

[[6 2 4]
 [8 6 9]
 [0 5 5]] 

 [[4 2 8]
 [2 6 0]
 [6 9 5]]


This first example does not use <code>np.einsum()</code> but it, rather, shows three calculations that we might make with the two arrays, respectively, 

- The dot product of the two arrays 
- Elementwise multiplication of the two arrays
- The dot product of the two arays, subsequently summed along axis 0
- The dot product of the two arays, subsequently summed along axis 1
- The dot product of the two arays, subsequently summed along both axes

In [16]:
''' Dot products/matrix-vector math mode '''
print('Dot Product\n',mat1@mat2)
print('\nDot Product, summed on axis=0\n',(mat1@mat2).sum(axis=0))
print('\nDot Product, summed on axis=1\n',(mat1@mat2).sum(axis=1))
print('\nDot Product, summed on both axes\n',(mat1@mat2).sum())

''' Elementwise/vectorized computations '''
print('\nElementwise Product\n', mat1*mat2)
print('\nElementwise Product, summed on axis=0\n',(mat1*mat2).sum(axis=0))
print('\nElementwise Product, summed on axis=1\n',(mat1*mat2).sum(axis=1))
print('\nElementwise Product, summed on both axes\n',(mat1*mat2).sum())

Dot Product
 [[ 52  60  68]
 [ 98 133 109]
 [ 40  75  25]]

Dot Product, summed on axis=0
 [190 268 202]

Dot Product, summed on axis=1
 [180 340 140]

Dot Product, summed on both axes
 660

Elementwise Product
 [[24  4 32]
 [16 36  0]
 [ 0 45 25]]

Elementwise Product, summed on axis=0
 [40 85 57]

Elementwise Product, summed on axis=1
 [60 52 70]

Elementwise Product, summed on both axes
 182


This first example of <code>np.einsum()</code> uses Einstein notation that denotes the dot product:

``` python
'ij,jk->ik'
```

Notably, the <code>j</code> relates to the column indices of the first input as well as the row indices of the second input, which indicates that the elements in the rows of the first input are to be multiplied by the columns in the second input, as is done with the dot product.  The <code>ik</code> indicates that the result has two dimensions with the row indices relating to the first input and the column indices relating to the second input, again, as is the case with the dot product.

Note that the absence of an output specification results in a dot product with the input specifications as shown here.

In [32]:
result = np.einsum('ij,jk->ik', mat1, mat2)
print(result)

[[ 52  60  68]
 [ 98 133 109]
 [ 40  75  25]]


In [33]:
result = np.einsum('ij,jk', mat1, mat2)
print(result)

[[ 52  60  68]
 [ 98 133 109]
 [ 40  75  25]]


It was claimed earlier that the order of the indices mattered, as is demonstrated below.  reversing the <code>i</code> and <code>k</code> in the output specification causes the output to be the transpose of the prior respective result.

In [34]:
result = np.einsum('ij,jk->ki', mat1, mat2)
print(result)

[[ 52  98  40]
 [ 60 133  75]
 [ 68 109  25]]


The two computations below sum along either of the axes depending whether the output is speciified to be related with the <code>i</code> or <code>j</code> indices.  <code>i</code> refers to the rows of the first input, and so the sum is along the columns.  Conversely, specifying the output with <code>k</code> sums along axis 0.

In [35]:
result = np.einsum('ij,jk->k', mat1, mat2)
print(result)

[190 268 202]


In [36]:
result = np.einsum('ij,jk->i', mat1, mat2)
print(result)

[180 340 140]


Summing along both axes with dot product being indicated with the inputs requires the <code>-></code> symbol with no output specification. 

In [37]:
result = np.einsum('ij,jk->', mat1, mat2)
print(result)

660


Elementwise multiplication, without summing, is down by listing the indices characters in the same order, with both indices characters also listed in the output specification.  

In [38]:
result = np.einsum('ij,ij->ij', mat1, mat2)
print(result)

[[24  4 32]
 [16 36  0]
 [ 0 45 25]]


Similarly to a previous example, one can generate the transpose result by switching the characters.

In [39]:
result = np.einsum('ij,ij->ji', mat1, mat2)
print(result)

[[24 16  0]
 [ 4 36 45]
 [32  0 25]]


Summing along axes is done as shown before with dot products.  Listing <code>i</code> will cause the summation to occur acoross the unlisted indices (<code>j</code>), that is across the columns as in <code>axis=1</code>.  Conversely listing <code>j</code> in the output specification causes summation as in <code>axis=1</code>.

In [40]:
result = np.einsum('ij,ij->i', mat1, mat2)
print(result)

[60 52 70]


In [41]:
result = np.einsum('ij,ij->j', mat1, mat2)
print(result)

[40 85 57]


Summing along all axes in accomplishing by omitting an output specification.

In [42]:
result = np.einsum('ij,ij', mat1, mat2)
print(result)

182


Einstein notation is just as applicable with vectors (single dimension arrays) but, of course, only one index character can be used with them since they have but one dimension.

In [22]:
vec_one = np.ones(mat1.shape[0])

In [23]:
print(np.einsum('ij,j',mat1,vec_one))

[12. 23. 10.]


In [24]:
print(np.einsum('ij,i',mat1,vec_one))

[14. 13. 18.]


In [27]:
print(np.einsum('i,ij',vec_one,mat1))

[14. 13. 18.]


In [28]:
print(np.einsum('i,ij->j',vec_one,mat1))

[14. 13. 18.]


In [29]:
print(np.einsum('ij,i->j',mat1,vec_one))

[14. 13. 18.]


In [30]:
print(np.einsum('ij,i->',mat1,vec_one))

45.0


In [31]:
print(np.einsum('ij,i->ij',mat1,vec_one))

[[6. 2. 4.]
 [8. 6. 9.]
 [0. 5. 5.]]


# Computing Distances with <code>np.einsum()</code>

In [12]:
start = time.time()
#result = np.sqrt(np.diag(q@q.T) -2*q@p.T + np.diag(p@p.T).reshape(-1,1))
result_ein = np.sqrt(np.einsum('ij,ij->i',q,q)[:,np.newaxis] - 2*q@p.T + np.einsum('ij,ij->i',p,p))

print('Exec. time: %s for %sx%s' % (str(float(time.time() - start)), str(n), str(n)))
print(result_ein[0,:5])

Exec. time: 0.0009982585906982422 for 100x100
[10.553866 10.057241  8.833829  9.928222  8.737532]


In [13]:
(result - result_ein)

array([[ 9.5367432e-07,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 9.5367432e-07,  9.5367432e-07,  0.0000000e+00, ...,
        -9.5367432e-07,  0.0000000e+00,  0.0000000e+00],
       [ 9.5367432e-07,  9.5367432e-07,  0.0000000e+00, ...,
         0.0000000e+00,  9.5367432e-07,  0.0000000e+00],
       ...,
       [ 1.9073486e-06,  9.5367432e-07,  9.5367432e-07, ...,
         9.5367432e-07,  9.5367432e-07,  9.5367432e-07],
       [ 9.5367432e-07,  9.5367432e-07,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)